# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 8091
    connection-timeout: 5000
    servlet:
        context-path: /


eureka:
  instance:
      hostname: localhost
      instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}}
      prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: liaotao-consumer-8091


